Show root formula if roots are irrational
AbdelRahmanRahal/QUADROOT pull request #1
Opened 2023-12-06 22:56 UTC by NihadBadalov

![image](https://github.com/AbdelRahmanRahal/QUADROOT/assets/32594553/bdf9239e-5aea-44df-977c-9f4a7d2a7748)

2023-12-08 01:35 UTC, AbdelRahmanRahal requested changes
This actually used to be how I had it, but I realised I only needed to show the root formulas for my assignments if they were imaginary. Still, it's an nice option. Fix these and I am 100% down.

2023-12-08 01:35 UTC, AbdelRahmanRahal commented on QUADROOT.py
> +        print(f'\nX = ( {-b} + {f"sqrt({d})" if decimal_point_amount(d**0.5) > 5 else {d**0.5}} ) / {2*a}\nX = ( {-b} - {f"sqrt({d})" if decimal_point_amount(d**0.5) > 5 else {d**0.5}} ) / {2*a}')
f-strings do not work on MicroPython v1.9.4, which is the version supported by Casio fx-9750GIII.

2023-12-08 01:35 UTC, AbdelRahmanRahal commented on QUADROOT.py
> +def decimal_point_amount(n: float) -> int:
Remove type annotations for backwards compatibility for Casio fx-9750GIII calculators.

2023-12-08 10:37 UTC, NihadBadalov commented on QUADROOT.py
> +def decimal_point_amount(n: float) -> int:
removed type annotations

2023-12-08 10:38 UTC, NihadBadalov commented on QUADROOT.py
> +        print(f'\nX = ( {-b} + {f"sqrt({d})" if decimal_point_amount(d**0.5) > 5 else {d**0.5}} ) / {2*a}\nX = ( {-b} - {f"sqrt({d})" if decimal_point_amount(d**0.5) > 5 else {d**0.5}} ) / {2*a}')
f-strings -> format() ✅

2023-12-09 13:22 UTC, AbdelRahmanRahal approved these changes
LGTM! I'll tweak some stuff later to make it look better on Casio displays. Good stuff!

2023-12-09 13:22 UTC, merged

2023-12-09 16:22 UTC, NihadBadalov commented
Epic